global:
  scrape_interval: 15s
  evaluation_interval: 15s
#  external_labels:
#    monitor: 'flask-flask_app.py'


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: flask_app_exporter
    static_configs:
      - targets:
          - web:5001
